export const RowFlags = {
  Retired: 1 << 0,
  HeliosRay: 1 << 1,
  HasThumbnail: 1 << 2,
};

export const ColorFlags = {
  b: 1 << 0,
  l: 1 << 1,
  n: 1 << 2,
  e: 1 << 3,
  g: 1 << 4,
  y: 1 << 5,
  p: 1 << 6,
  u: 1 << 7,
  w: 1 << 8,
  r: 1 << 9,
};

export const TagsFlags = {
  ab: 1n << 0n,
  bt: 1n << 1n,
  bw: 1n << 2n,
  bp: 1n << 3n,
  braids: 1n << 4n,
  ch: 1n << 5n,
  cl: 1n << 6n,
  dr: 1n << 7n,
  left: 1n << 8n,
  right: 1n << 9n,
  fy: 1n << 10n,
  hair: 1n << 11n,
  jy: 1n << 12n,
  mh: 1n << 13n,
  ml: 1n << 14n,
  tack: 1n << 15n,
  bay: 1n << 16n,
  black: 1n << 17n,
  red: 1n << 18n,
  cream: 1n << 19n,
  dun: 1n << 20n,
  cfan: 1n << 21n,
  gray: 1n << 22n,
  leo: 1n << 23n,
  spot: 1n << 24n,
  pinto: 1n << 25n,
  roan: 1n << 26n,
  seal: 1n << 27n,
  afk: 1n << 28n,
  ame: 1n << 29n,
  emb: 1n << 30n,
  jpn: 1n << 31n,
  myt: 1n << 32n,
  pir: 1n << 33n,
  pri: 1n << 34n,
  afr: 1n << 35n,
  stars: 1n << 36n,
  fla: 1n << 37n,
  fs: 1n << 38n,
  gs: 1n << 39n,
  gil: 1n << 40n,
  jcg: 1n << 41n,
  mus: 1n << 42n,
  obb: 1n << 43n,
  obi: 1n << 44n,
  pg: 1n << 45n,
  spo: 1n << 46n,
  rb: 1n << 47n,
  swirl: 1n << 48n,
  ann: 1n << 49n,
  nyd: 1n << 50n,
  esp: 1n << 51n,
  spk: 1n << 52n,
  val: 1n << 53n,
  buck: 1n << 54n,
  run: 1n << 55n,
  drs: 1n << 56n,
  aer: 1n << 57n,
  ghd: 1n << 58n,
  jump: 1n << 59n,
  lysi: 1n << 60n,
  pos: 1n << 61n,
  st: 1n << 62n,
  trot: 1n << 63n,
  walk: 1n << 64n,
  abs: 1n << 65n,
  anb: 1n << 66n,
  ant: 1n << 67n,
  anf: 1n << 68n,
  ani: 1n << 69n,
  anm: 1n << 70n,
  anr: 1n << 71n,
  cute: 1n << 72n,
  lig: 1n << 73n,
  pt: 1n << 74n,
  rea: 1n << 75n,
  retro: 1n << 76n,
  sp: 1n << 77n,
  tsp: 1n << 78n,
  sno: 1n << 79n,
  wat: 1n << 80n,
  win: 1n << 81n,
};

export const parseFlags = <Key extends string = string>(
  value: number | bigint,
  set: Record<Key, number | bigint>,
) => {
  const keys: Key[] = [];
  for (const [key, flag] of Object.entries(set)) {
    if (typeof value === "bigint") {
      if (((flag as bigint) & value) === flag) {
        keys.push(key as Key);
      }
    } else {
      if (((flag as number) & value) === flag) {
        keys.push(key as Key);
      }
    }
  }
  return keys;
};

export const colorNames: Record<keyof typeof ColorFlags, string> = {
  b: "black",
  l: "blue",
  n: "brown",
  e: "green",
  g: "gray",
  y: "yellow",
  p: "pink",
  u: "purple",
  w: "white",
  r: "red",
};

export const horseTypeNames: Record<string, string> = {
  dok: "Donkey",
  dkp: "Donkey pegasus",
  dku: "Donkey unicorn",
  dkw: "Donkey winged unicorn",
  dh: "Draft horse",
  dhp: "Draft pegasus",
  dhu: "Draft unicorn",
  dhw: "Draft winged unicorn",
  p: "Pony",
  pp: "Pony pegasus",
  pu: "Pony unicorn",
  pwu: "Pony winged unicorn",
  rh: "Riding horse",
  rp: "Riding pegasus",
  riu: "Riding unicorn",
  rwu: "Riding winged unicorn",
};

export const breedNames: Record<string, string> = {
  at: "Akhal-Teke",
  ac: "American Curly",
  am: "Americas",
  ah: "Arabian Horse",
  dp: "Draft Pony",
  fri: "Friesian",
  haf: "Haflinger",
  hd: "Heavy Draft",
  ic: "Irish Cob",
  ld: "Light Draft",
  mw: "Marwari",
  nor: "Nordics",
  spy: "Sport Pony",
  tb: "Thoroughbred",
  tr: "Trotter",
  wb: "Warmblood",
};

export const tagNames: Record<keyof typeof TagsFlags, string> = {
  ab: "above/below",
  bt: "big tail",
  bw: "big wings",
  bp: "body paint",
  braids: "braids",
  ch: "chains",
  cl: "clothing",
  dr: "draconic",
  left: "facing left",
  right: "facing right",
  fy: "foal",
  hair: "hairy",
  jy: "jewelry",
  mh: "multi-heads",
  ml: "multi-legs",
  tack: "tack",
  bay: "bay",
  black: "black",
  red: "red",
  cream: "cream",
  dun: "dun",
  cfan: "fantasy",
  gray: "gray",
  leo: "leopard",
  spot: "pangare",
  pinto: "pinto",
  roan: "roan",
  seal: "seal bay",
  afk: "africa",
  ame: "america",
  emb: "emblems",
  jpn: "japan",
  myt: "mythos",
  pir: "pirates",
  pri: "primeval",
  afr: "animal friends",
  stars: "stars",
  fla: "flames",
  fs: "food",
  gs: "space",
  gil: "gilded",
  jcg: "gems",
  mus: "music",
  obb: "beside object",
  obi: "inside object",
  pg: "plants",
  spo: "sport",
  rb: "rainbows",
  swirl: "swirls",
  ann: "anniversary",
  nyd: "new years",
  esp: "spring",
  spk: "spooky",
  val: "valentines",
  buck: "bucking",
  run: "running",
  drs: "dressage",
  aer: "aerial",
  ghd: "grazing",
  jump: "jumping",
  lysi: "sitting",
  pos: "posing",
  st: "standing",
  trot: "trotting",
  walk: "walking",
  abs: "abstract",
  anb: "an-bird",
  ant: "an-fantasy",
  anf: "an-fish",
  ani: "an-insect",
  anm: "an-mammal",
  anr: "an-reptile",
  cute: "cute",
  lig: "light",
  pt: "painting",
  rea: "realistic",
  retro: "retro",
  sp: "steampunk",
  tsp: "transparent",
  sno: "snow",
  wat: "water",
  win: "wind",
};

export const maxUses = [100, 200, 300, 400, 500, 600, 700, 800, 900] as const;
export type MaxUses = (typeof maxUses)[number];
